### ISSUE TITLE
Donate an arbitrary amount to the event

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#110]
Some events don't require a entrance fee but rely on arbitrary donations from attendees. 
We should support that.

**Comment by cbellone** [comment]
should be done :)

@mg-1999 could you please provide a Dutch translation for:

`reservation-page-complete.thanks-for-your-support=Thank you very much for your support!`

thank you!!

**Comment by mg-1999** [comment]
The translation is:

`Hartelijk dank voor uw steun!`

You're welcome :)

Op wo 6 jul. 2016 07:26 schreef Celestino Bellone <notifications@github.com
>:

> should be done :)
>
> @mg-1999 <https://github.com/mg-1999> could you please provide a Dutch
> translation for:
>
> reservation-page-complete.thanks-for-your-support=Thank you very much for
> your support!
>
> thank you!!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/exteso/alf.io/issues/110#issuecomment-230674071>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGmkdrWtGu6hi4nG_7aaNtXS0WjNahTNks5qSzxogaJpZM4H4ZUz>
> .
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by syjer** [comment]
issue with subtotal (which cause an issue with the paypal option) and vat:

using the test event, add a donation with "user-defined" quantity and VAT "use event settings".

Buy a 5chf ticket, and donate 11chf ->

in the order summary, we have 

- 1 x 5chf ticket
- 1 x 10.19chf donation (<- the vat has been removed)

(vat of 1.19 CHF)

In the payment process, if we use paypal, this will cause the following error: "Item amount must add up to specified amount subtotal (or total if amount details not specified)".

Expected:

- 1 x 5chf ticket
- 1 x 11chf donation

(vat should be 1.28)

I guess that we will need to check the case vat excluded.

**Comment by syjer** [comment]
it seems that an error in the VAT calculation has been introduced

**Comment by cbellone** [comment]
https://github.com/exteso/alf.io/commit/53fdd952ac8e87845e8ff1226daa2e964f38a8bc should fix the VAT application problem. 
But VAT calculation/application needs to be simplified. I will open another issue for that.

**Comment by cbellone** [comment]
done!
