### ISSUE TITLE
Support additional items

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#111]
Event organizers should be able to sell "additional items", such as event T-Shirts, upgrade packages etc.

**Comment by syjer** [comment]
- rename current additional items in donations
 - necessary feature: mandatory additional item (1 for each ticket in a reservation) (for legal reasons)

**Comment by syjer** [comment]
TODO:

 - [ ] select only valid MANDATORY_ONE_FOR_TICKET (currently select all)
 - [ ] validation logic for the others policy
 - [ ] ui admin
 - [ ] ui user

**Comment by syjer** [comment]
done!

**Comment by cbellone** [comment]
I have defined an additional option mandatory, one per ticket:

![image](https://cloud.githubusercontent.com/assets/3385346/26454672/0e5f6f2c-4168-11e7-99ce-e02f854ec56e.png)

then I found the following errors:

- missing data on edit
![image](https://cloud.githubusercontent.com/assets/3385346/26454786/604ca958-4168-11e7-9f67-e245122025b2.png)

- the supplement has been applied twice (instead of just once) on the reservation

![image](https://cloud.githubusercontent.com/assets/3385346/26454599/d8f990f6-4167-11e7-86a4-fcd4c4ccceb8.png)

**Comment by syjer** [comment]
second issue fixed.

**Comment by syjer** [comment]
first issue fixed too
