### ISSUE TITLE
Assign a discount code to a specific category

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#112]
It should be possible to assign a discount code to a specific category, rather than to all the categories, as it is now.

**Comment by syjer** [comment]
TODO:

- [ ] update queries
- [ ] update admin
- [ ] update user ui
- [ ] update business logic

**Comment by BunsenMcDubbs** [comment]
I pulled this and got this error when the start up script started a database migration 

```
Migration V15_1.8.6__ADD_CATEGORIES_TO_PROMO_CODE.sql failed
------------------------------------------------------------
SQL State  : 42000
Error Code : 1067
Message    : Invalid default value for 'valid_to'
Location   : alfio/db/MYSQL/V15_1.8.6__ADD_CATEGORIES_TO_PROMO_CODE.sql (<path to>/alf.io/build/resources/main/alfio/db/MYSQL/V15_1.8.6__ADD_CATEGORIES_TO_PROMO_CODE.sql)
Line       : 18
Statement  : alter table promo_code add column categories varchar(2048)
```

I think this is the same issue as #131 

I would fix it myself but I'm not sure what @cbellone did exactly.

**Comment by cbellone** [comment]
Hi @BunsenMcDubbs 

I tested the migration scripts on a clean database:

`Server version: 5.7.13 MySQL Community Server (GPL)`

(should be latest version available on docker hub) but I cannot reproduce your issue. 

Which version are you using? 

Thanks,
Celestino

**Comment by syjer** [comment]
should be completed.
