### ISSUE TITLE
Cannot create event

### ISSUE THREAD

**Issue by treed593** [exteso/alf.io#113]
Running on heroku

Inspect Element returns the following error:

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'".

Is there something I can check to get this working?

**Comment by cbellone** [comment]
Hi Trevor,
Thanks for using alf.io!

There is a known issue with the calendar widget, so you should double check
all the dates (open the date selection widget, select date and time, then
click on "apply") before submitting the form.

Please check:

- Event start/end date
- ticket categories inception /expiration date

Thanks,
Celestino

**Comment by treed593** [comment]
Thank You, That worked!
