### ISSUE TITLE
Login issues on Heroku

### ISSUE THREAD

**Issue by treed593** [exteso/alf.io#116]
Is there a reason that authentication would be hit or miss when running on Heroku?

I am not getting any authentication error, but when I enter the password I get redirected back to /authentication.

**Comment by cbellone** [comment]
This was a general problem rather than heroku-specific. Anyway it should be solved now. 
Will be released with the upcoming 1.7.2.
It would be great if you could test it on heroku before the release

**Comment by treed593** [comment]
I would be glad to test it, is a war available, or should I build from
github source?

**Comment by cbellone** [comment]
you can find the latest release here: https://github.com/exteso/alf.io/releases/tag/1.7.2-RC1

many thanks for your effort!

**Comment by treed593** [comment]
Everything seems to be working on heroku. I however do not see a logout button or a place to change the admin password? Is the username supposed to be clickable?

**Comment by cbellone** [comment]
OK, thanks. Closing this issue as the problem has been fixed.

At the moment there is no logout/"reset password" for admin buttons.
Could you please open another issue for that? Thank you!
