### ISSUE TITLE
Cannot create new events

### ISSUE THREAD

**Issue by muc2sf** [exteso/alf.io#119]
admin panel - create new events, ticket category remains in red after entered, preventing from creating new events, see screenshot: https://www.dropbox.com/s/neafspv9lsl6pwy/Screenshot%202016-04-13%2019.55.48.png?dl=0
tried with 1.7.1 & 1.7.2, no error on the server side

**Comment by cbellone** [comment]
Hi,

And thanks for using alf.io!

It should be a known issue, please see
https://github.com/exteso/alf.io/issues/113

We'll fix the validation feedback in the next version (1.8)

**Comment by cbellone** [comment]
closed for inactivity
