### ISSUE TITLE
set max file size for attachments

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#128]
got on Mysql:

SQL [insert into file_blob (id, name, content_size, content, content_type, attributes) values(?, ?, ?, ?, ?, ?)]; Packet for query is too large (1490588 > 1048576). You can change this value on the server by setting the max_allowed_packet' variable.

we should set a maximum file size (512KB?)

**Comment by Praitheesh** [comment]
I would like to contribute this issue. Could you please explain more in which page getting this error and how to reproduce ?

**Comment by syjer** [comment]
Hi @Praitheesh , you will need to use a mysql db for reproducing this error.

When you create a new event, try to upload a really big image, mysql should fail. The check could be done client side though

**Comment by Praitheesh** [comment]
fixed with define max upload limit to 1MB and create the pull request. Thanks

**Comment by Praitheesh** [comment]
It is fixed, can be close. Thanks.

**Comment by syjer** [comment]
closing. Thank you @Praitheesh
