### ISSUE TITLE
Implement auditing

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#135]
We should log all operations like:
- event creation/modification
- reservation complete
- reservation expired
- check-in
  ...

**Comment by thiyagu06** [comment]
Is this issue has been implemented?

**Comment by cbellone** [comment]
Hi @thiyagu06,

no, it has been scheduled for next release. Currently we're analyzing the impact and figuring out how to implement it.
Do you have any suggestions / do you want to help with this?

Thank you!
Celestino

**Comment by thiyagu06** [comment]
Hi @cbellone 

yes.. I would like to help to fix this issue. Please include in discussions.

**Comment by cbellone** [comment]
OK, great! We'll involve you after we close the release 1.8 (it would happen in the next few days, hopefully). In the meantime please subscribe to our mailing list https://groups.google.com/d/forum/alfio

See you soon!

**Comment by cbellone** [comment]
Hi @thiyagu06 
still interested in helping with this task?
Do you have already an idea on how could we implement it?

Thanks
Celestino

**Comment by thiyagu06** [comment]
Hi @cbellone ,

Yes.. I am ready take up this task..

**Comment by cbellone** [comment]
That's great!

The goal of the task is to offer the "auditing" functionality in the admin tool, so that users can see what's happened to a particular ticket or reservation.

Our idea would be to create an auditing table, and then store the modification in it. The table should contain:

```
SESSION_ID: The java session ID of the user
TIMESTAMP: The timestamp of the modification
ACTION: varchar/enum, possible values: INSERT, UPDATE, ...
ENTITY_TYPE: varchar/enum, possible values: TICKET, CATEGORY, ...
ENTITY_ID: The id of the modified entity
MODIFICATIONS: JSON with the modified properties (for each property: old_value and new_value)
```
how does it sound?

**Comment by thiyagu06** [comment]
yeah sure.. thats fine. If an with entity with same id is audited multiple times, based modifications column it will be difficult to find the history of the changed values for a particular columns. give your thoughts on this..

**Comment by cbellone** [comment]
I am not sure I understand your point. Anyway I see two possible scenarios: 

1) Multiple modifications at the same time

That could happen if a user modifies two or more properties of the entity in the same transaction (e.g. category price and max seats). In this case the MODIFICATIONS json will contain two pairs (old and new value), one for category price and the other one for max seats 

2) Entity modified multiple (n) times
In this case we'll have (n) rows in the table, each one corresponding to a particular modification.

Either way we can display the updated history on the admin GUI, sorting the result set by timestamp. Then it would be an easy task to implement a full-text search on the client, so that the admin can see how a particular column has been modified.

Does that answer your question?

**Comment by thiyagu06** [comment]
yeah..perfect. I just want know json format for modification. then ,I will look into the code and discuss on the design.

**Comment by cbellone** [comment]
Hi @thiyagu06 

I would say something like that:
```
[{
   "propertyName": "property1",
   "oldValue": "old",
   "newValue":"new"
}, {
   "propertyName": "property2",
   "oldValue": "old2",
   "newValue":"new2"
}]
```

**Comment by syjer** [comment]
can be considered done, finally
