### ISSUE TITLE
Update Angular $tooltip to $uibTooltip

### ISSUE THREAD

**Issue by BunsenMcDubbs** [exteso/alf.io#138]
When creating new events (`http://localhost:8080/admin#/events/new`), opening the Javascript console reveals these deprecation warnings:
```
$tooltip is now deprecated. Use $uibTooltip instead.
tooltip-popup is now deprecated. Use uib-tooltip-popup instead.
```

This should be a simple fix. I can take care of it.

**Comment by syjer** [comment]
Should be fixed, thank you @BunsenMcDubbs  :D
