### ISSUE TITLE
TicketReservationManager.countAvailableTickets count tickets with "PENDING" status as available

### ISSUE THREAD

**Issue by syjer** [exteso/alf.io#144]
TicketReservationManager.countAvailableTickets count tickets with "PENDING" status as available.

This could be confusing for the user in the ticket page.

**Comment by syjer** [comment]
the current status are:

```FREE, PENDING, TO_BE_PAID, ACQUIRED, CANCELLED, CHECKED_IN, EXPIRED, INVALIDATED, RELEASED, PRE_RESERVED```

The query is:

select count(*) from ticket where status not in ('ACQUIRED', 'CHECKED_IN', 'TO_BE_PAID', 'INVALIDATED', 'CANCELLED')  and category_id = :categoryId and event_id = :eventId

**Comment by cbellone** [comment]
should be fixed now.
