### ISSUE TITLE
Show contextualized error message when ticket purchase doesn't work

### ISSUE THREAD

**Issue by alessandro-giardina** [exteso/alf.io#147]
Sometimes, when I press the "Pay X.XX EUR" button, nothing happens. The page seems to reload, but I don't get neither error messages neither other kinds of feedback.
The cause of this behavior is a misconfiguration of the event.
It could be useful to show a contextualized error message when that button doesn't work, so that the administrator become aware of the underlying configuration problem.

**Comment by cbellone** [comment]
should be solved now
