### ISSUE TITLE
Additional fields: optional/mandatory

### ISSUE THREAD

**Issue by alessandro-giardina** [exteso/alf.io#153]
As administrator, it would be useful if I could define each additional field as optional or mandatory, so that the attendees are forced to provide me essential information.

**Comment by syjer** [comment]
:+1: the initial groundwork for this feature is actually implemented :)

**Comment by Praitheesh** [comment]
I'm happy to work on this issue.

**Comment by Praitheesh** [comment]
does required field need to editable when edit field in event details page ? I noticed only `ticket_field_description` is editable not `ticket_field_configuration`.

**Comment by cbellone** [comment]
Closing it. Well done @Praitheesh!!

Btw, it's OK not to edit the "required" flag, because it could lead to incoherent data.
