### ISSUE TITLE
Numeric fields under the “Seats and payment info” allow negative numbers

### ISSUE THREAD

**Issue by alessandro-giardina** [exteso/alf.io#189]
"Max tickets", "Regular Price" and "VAT (%)" fields allow filling in with negative values.
The same for the "Price" field in the ticket categories.

![negative numbers](https://cloud.githubusercontent.com/assets/4352322/18208718/d65c9896-7130-11e6-9ded-96669851cdc4.jpg)

**Comment by syjer** [comment]
Should be fixed :)
