### ISSUE TITLE
Languages always mandatory in donation options

### ISSUE THREAD

**Issue by alessandro-giardina** [exteso/alf.io#190]
In defining the types of donations, it forces me to fill in titles and descriptions in each of the 4 languages, even though in the main part of the event I choose to use only a subset of the available languages

![mandatory languages](https://cloud.githubusercontent.com/assets/4352322/18208891/9f4bc6dc-7131-11e6-82c0-4eafa3f76a26.jpg)

**Comment by syjer** [comment]
fixed :)
