### ISSUE TITLE
"An unexpected error has occurred. Please try again." trying to buy a paid ticket

### ISSUE THREAD

**Issue by alberanid** [exteso/alf.io#193]
Trying to pay for a ticket (on step 2), I've received the "An unexpected error has occurred. Please try again." error.  Not having access to the server side, I can't debug it further (noting on the client-side).

The event is hackinbo-test, on your 'test' subdomain.

This is most probably due to some error with the sandbox Paypal REST API client ID I've used or from the buyer account (again, from the same sandbox).  Maybe you don't support Paypal sandbox mode at all?

**Comment by syjer** [comment]
Hi, @alberanid . 

The paypal configuration was set to 

- "Enable live mode for Paypal"  "on"
- sandbox keys

That's why you received the error. I've set to off the enable live mode and it seems to work as expected :)

**Comment by cbellone** [comment]
ciao @alberanid ,
and thanks for testing alf.io!!

We have the following error on our log:
Server returned HTTP response code: 401 for URL: **https://api.paypal.com/v1/oauth2/token**
no call has been made on the sandbox.

I have checked the configuration, and it looks like the "live" mode for paypal has been enabled

![image](https://cloud.githubusercontent.com/assets/3385346/18233032/688d28c2-72dd-11e6-8d0d-d79f657f9fac.png)

once I disabled it

**Comment by syjer** [comment]
Maybe it's a UI problem, when changing the value of the switch, you should save the configuration. Normally it should apply on change ?

**Comment by alberanid** [comment]
ops, my fault: I was playing with the GUI and forgot Live mode on.

I can confirm that it works correctly. 

@syjer: I'm closing this issue; maybe you want to open another to improve the error message, for this case.


Thanks!
