### ISSUE TITLE
Suspend waiting queue

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#201]
Sometimes could be useful to suspend automatic ticket reassignment done by waiting queue. 
By doing that we could still let people subscribe and release tickets, if possible.

**Comment by alessandro-giardina** [comment]
It could be useful to define upfront a "limited" waiting list, so that it can contain only a maximum number of elements.

**Comment by alessandro-giardina** [comment]
It could be useful to show the user his/her position in the waiting list
