### ISSUE TITLE
Allow event organizer to postpone the expiration date for pending tickets

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#218]
In the "Manual confirmation" table of "Pending Reservations" view, it could be useful to have a calendar widget to change the expiration date. Sometimes, they may ask for some more days because of company payment processes.

I would propose to move the "expiration date" column as the last one of the table, followed by a blue button with the "Postpone" label. It should be placed before the green and red buttons in each row.
When the user clicks on the button a calendar widget popup, to select the date and POST the new date to the server. 
What about creating an action url (something like /actions/postpone-pending-tickets) in order to allow for a more complex business logic to validate the operation? (if needed)

thinking of UX: 
1. there should be a "save" button inside the calendar widget to clarify that the change is sent. Additionally if the user clicks "cancel" or outside the widget, it is closed without applying any change.
2. The new date should immediately be visualized in the gui (without reloading the data from the server)

**Comment by cbellone** [comment]
see #234
