### ISSUE TITLE
Send Invoice for pending reservations

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#219]
it could be useful to send an invoice to a customer that has selected an offline payment.
He could easily forward that to the accounting team.

It should be a PDF template with a couple of logos (organizer and event), the list of items included, total price and VAT, payment instructions and expiration date (maybe increasing it of X days)

It should not be sent to all offline reservations, only companies may need that.
We could have a Reservation type radio button, per default on "Private" but could be changed to "Company".

**Comment by cbellone** [comment]
The invoice should also have a number (sequential or pattern, user-defined)

**Comment by syjer** [comment]
Hi @mg-1999 ,

Could you help us with the NL translations for the following texts?

- invoice.invoice=Invoice
- reservation-page-complete.download-your-invoice=Download your invoice
- reservation-page-complete.download-your-receipt=Download your receipt
- invoice.to=Invoice to:
- invoice.number=Invoice number:
- invoice.vat-invoice=VAT Invoice
- invoice.payment-instruction=Payment instruction
- invoice.payment-contact=Send us an e-mail ({0}) with the proof of payment. You will receive a confirmation e-mail.
- invoice.payment-instruction-no-later-than=To complete the transaction, you have to make the payment not later than {0} using the details below.
- invoice.account-number=Account number: <strong>{0}</strong>
- invoice.payment-to=Payment to:
- invoice.payment-reason=With <strong>{0}</strong> as a payment reason.

**Comment by mg-1999** [comment]
Hey @syjer,

Here you have it:
```
invoice.invoice=Factuur
reservation-page-complete.download-your-invoice=Download je factuur
reservation-page-complete.download-your-receipt=Download je bon
invoice.to=Factuur aan:
invoice.number=Factuurnummer:
invoice.vat-invoice=BTW Factuur
invoice.payment-instruction=Betaalinstructies
invoice.payment-contact=Stuur een email ({0}) met het bewijs van betaling en je ontvangt de bevestigingsmail.
invoice.payment-instruction-no-later-than=Om de betaling te kunnen voltooien, moet je voor {0} betaald hebben met de details hieronder.
invoice.account-number=Account nummer: {0}
invoice.payment-to=Betaling aan:
invoice.payment-reason=Met {0} als betalingsomschrijving.
```

I don't know the context of the sentences so I will fix some translation issues when I know the context.

You're welcome :)

**Comment by syjer** [comment]
thanks @mg-1999  ! 

The context is a pdf document which is an invoice  :)
