### ISSUE TITLE
Event time zone  issue

### ISSUE THREAD

**Issue by antonyfrance** [exteso/alf.io#228]
Hi,
**Amazing job  for  the Alf.io  team.**  I am actualy  in tests steps.   Without documation  for the configuration in the dashboard ... may be  that  something   is wrong... **but  i can not   create  a event !**!
(i have Organizations and users)

When a put my location (34 avenue malraux 37000 tours)    i can see : 

**No TimeZone found for location having coordinates: 47.3974492,0.6969276999999999**

ANd i have nothing in the Event time zone field.

Have you got user documentation ? i would like check all parametres ...

I will  go  more deeper in your  alf.io project , and  may be  that  i could help to translate in french !

Best regards !

**Comment by cbellone** [comment]
Hi @antonyfrance 

thank you for giving alf.io a try!

I think that your issue could be related to missing grants on google API.

Could you please configure your Google API project as explained in https://github.com/exteso/alf.io/issues/76#issuecomment-143015876 ?

Please let me know if that would solve the problem.

> Have you got user documentation ? i would like check all parametres ...

we don't have much user documentation yet. Any contribution would be more than welcome!

> I will go more deeper in your alf.io project , and may be that i could help to translate in french !

that would be great! :-)

Celestino

**Comment by antonyfrance** [comment]
Hi  Celestino !

Thank so much . Yes, it was missing   3 google api.
I    continue to explore  alf.io. 

I seem  1.8.1 works very well. i may  explore some configuration misatkes. 

great  work !

Antony
