### ISSUE TITLE
Hide expired events after 2 weeks from end date

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#233]
After some time, expired events are not so important anymore to be immediately loaded in the dashboard list.
To speed up rendering of the page with a lot of events (above 20), expired events should be loaded with a separate call and be graphically hidden (open a sub-list to view all of them)

**Comment by yankedev** [comment]
for expired events it can also be interesting to see number of sold tickets directly in the list (or some additional info)

**Comment by cbellone** [comment]
see also #186

**Comment by syjer** [comment]
Todo: 

 - [ ] currently the cutoff date is exactly the expiration date, is the 2 week time lag a good idea?
 - [ ] show sold tickets/places statistic

**Comment by syjer** [comment]
done :)
