### ISSUE TITLE
Validation error message when assigning tickets

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#238]
When POSTing for assigning a ticket on a reservation with 15 tickets I got an error 500 when calling this url:
https://test.alf.io/event/cyber-risk/reservation/e0fa9783-48d9-4648-bb7b-ee129db42aec/ticket/1b3fa574-acec-4454-b0d9-cb833c3a28af/assign

But the ticket is correctly assigned and an email is send to the assignee mail 

In the GUI you correctly see the error message

**Comment by syjer** [comment]
(there were multiple issues:

 - first time that we are loading templates that references other templates (see changes in DataSourceConfiguration)
 - elementNamePrefix in model was required
 - other minor stuff
