### ISSUE TITLE
Display pending reservations in the event detail

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#244]
The should appear in the pending reservation screen

**Comment by syjer** [comment]
Make a list of all the reservations, with link to the reservation view

**Comment by syjer** [comment]
consider:
 - migration add event_id in tickets_reservation.

**Comment by syjer** [comment]
TODO:

 - [ ] base ui (table)
 - [ ] filter
 - [ ] link to reservation view

**Comment by syjer** [comment]
can be considered done.
