### ISSUE TITLE
xhr handling issue when handling js geolocation task

### ISSUE THREAD

**Issue by kwdebr** [exteso/alf.io#250]
We have been using Alf.io for about 4 months now.  Initially we had no problems creating new events.  Since a few weeks now, out of the blue, we have problems with the google maps API.  When we define an address, we get an immediate response of "No location found for....".  We also have no access to the "Event Time Zone" field which remains blank.  This blocks us to complete and save new events.

With the Mozilla Firefox developer tool I discovered that the problem is at the xhr level.
GET https://alfio-staproeselare.rhcloud.com/admin/api/location/geo.json?location=Meenseheirweg%2020,%208800%20Roeselare

Querystring:  location=Meenseheirweg 20, 8800 Roeselare

headers:
Host: alfio-staproeselare.rhcloud.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: application/json, text/plain, */*
Accept-Language: nl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
X-CSRF-TOKEN: 6f29c8c0-1f2f-4b03-808d-e5455251bedf
Referer: https://alfio-staproeselare.rhcloud.com/admin
Cookie: JSESSIONID=JVuIYrNWwaaoYyRpvZ6_t5Lu.alfio-staproeselare.rhcloud.com; GEAR=local-56ab28a289f5cfd4d20000c7
Connection: keep-alive

produces a 404 error....

Any suggestions on how we can solve this?

**Comment by cbellone** [comment]
Hi @kwdebr ,

did you receive my answer on the mailing list? https://groups.google.com/d/msg/alfio/8phtViHoOu0/H5DgnAu7CQAJ

anyway it looks like that your google API credentials aren't valid anymore. 
Could you please double-check it?

**Comment by kwdebr** [comment]
We will dig into this tomorrow and keep you informed.  thx for the fast reply.
Kurt


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Celestino Bellone <notifications@github.com> Date: 11/30/16  19:01  (GMT+01:00) To: "exteso/alf.io" <alf.io@noreply.github.com> Cc: kwdebr <kurt.debrouwer@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [exteso/alf.io] xhr handling issue when handling js geolocation task (#250) 
Hi @kwdebr ,
did you receive my answer on the mailing list? https://groups.google.com/d/msg/alfio/8phtViHoOu0/H5DgnAu7CQAJ
anyway it looks like that your google API credentials aren't valid anymore.

Could you please double-check it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/exteso/alf.io","title":"exteso/alf.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/exteso/alf.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cbellone in #250: Hi @kwdebr ,\r\n\r\ndid you receive my answer on the mailing list? https://groups.google.com/d/msg/alfio/8phtViHoOu0/H5DgnAu7CQAJ\r\n\r\nanyway it looks like that your google API credentials aren't valid anymore. \r\nCould you please double-check it?"}],"action":{"name":"View Issue","url":"https://github.com/exteso/alf.io/issues/250#issuecomment-263946669"}}}

**Comment by naqi** [comment]
@kwdebr Is there a solution to this? I can't create an event without time zone and no matter what key I generate always leads to 404 'No location found for address'

**Comment by cbellone** [comment]
Hi @naqi 
please check the permissions, as per https://github.com/exteso/alf.io/issues/76#issuecomment-143015876

please note that the Google server API key can't be restricted to a particular address, unless you're running alf.io on a dedicated server with a fixed IP

Hope that this helps

**Comment by cbellone** [comment]
Closing it. 
Starting from 1.12, we won't need "server" keys anymore, see #304
