### ISSUE TITLE
Support for Payment Gateway Library - Omnipay [Feature/Enhancement Request] 

### ISSUE THREAD

**Issue by drjagan** [exteso/alf.io#257]
Alf.io presently supports only one payment gateway out of the box - Stripe. (afaik)
[Omnipay, a robust payment processing library](https://github.com/thephpleague/omnipay) offers support for ~25 payment gateways (and growing). 
If Alf.io could integrate Omnipay (or any other payment processing gateway), it would remove one significant bottleneck allow it to be used all over the world without constraint. 
Please consider this request for enhancement. 

Thank you

**Comment by cbellone** [comment]
Hi @drjagan,
thanks for the hint. 
Unfortunately it's not possible to integrate omnipay because it is a PHP library and Alf.io is written in Java.
