### ISSUE TITLE
MediaStreamTrack.getSources() is deprecated and removed from Chrome

### ISSUE THREAD

**Issue by mg-1999** [exteso/alf.io#265]
The web ticketscan gave me this error `Your browser does not support MediaStreamTrack.getSources API.`

I did some digging and it is deprecated and removed in Chrome. See the issue below for a possible solution.
https://www.chromestatus.com/feature/4765305641369600

**Comment by syjer** [comment]
thanks for reporting it, I'll take care of it :)

**Comment by syjer** [comment]
should be fixed
