### ISSUE TITLE
notify organizer of expiring pending payments

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#277]
The system should notify the organizer of expiring pending payment. So the organizer can optionally extend the expiration date, if required

**Comment by syjer** [comment]
(notification via email)

**Comment by syjer** [comment]
The day before the expiration, an email must be sent containing a list of all expiring pending payment, with a link for each of them so they can be extended.

**Comment by syjer** [comment]
1) run cron job each hour
2) check which event has the hour 5:00 local time of the event
3) select all reservations expiring next day (local day of the event)

**Comment by syjer** [comment]
done
