### ISSUE TITLE
send reservation notification to multiple addresses

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#285]
Sometimes it could be useful to send the reservation notification to multiple addresses. We should let the organizer configure how many people should receive the notification

**Comment by syjer** [comment]
TODO: 

 - [ ] update db to add new cc field in email table
 - [ ] update db to add email list field in  event and organization table
 - [ ] update admin ui
 - [ ] wire up the cc logic in the reservation notification

**Comment by syjer** [comment]
done
