### ISSUE TITLE
promo codes

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#29]
Support the definition (through admin area) of a set of "generic" discount codes, which should apply on a limited timeslot, should be linked to the event and should affect only visible categories.

The BUC is:

a user inserts the promo code "HEY-HEY-PICK-ME" in the main page. If the given code matches exactly (case-insensitive comparison) a promo code defined for the current event, then the discount will be applied; otherwise we'll search for special price codes, as today

**Comment by syjer** [comment]
reminder: add note about the fact that a code can be applied only once at a time.

**Comment by syjer** [comment]
Should be done.
