### ISSUE TITLE
Feature Request: Show which tokens have already been sent out

### ISSUE THREAD

**Issue by alexdobo** [exteso/alf.io#290]
Currently (unless I'm dumb and don't know how to use it properly), for a restricted event there isn't an easy way to see which tokens you have emailed out.
It would be great if I could click on the tokens tag and see which ones have been emailed out, and which ones are still unassigned.

A couple other things I thought of while I was sending out tokens:
It would be nice if I didn't have to include the tokens in the ### .csv file I upload, and that it would automatically assign them.
There also isn't a good way of copying all of the tokens to get them ready to put in the .csv file.

Maybe a compromise would be an option to download a pre-formatted .csv file with the tokens already there.

**I have really enjoyed using alf.io, please keep up the great work!**

**Comment by cbellone** [comment]
Hi @alexdobo ,

thank you for using alf.io!

> Currently (unless I'm dumb and don't know how to use it properly), for a restricted event there isn't an easy way to see which tokens you have emailed out.
It would be great if I could click on the tokens tag and see which ones have been emailed out, and which ones are still unassigned.

Yes, I agree. At the moment you can only see the email history on the "send invitation" page

![image](https://cloud.githubusercontent.com/assets/3385346/25585037/f5c14076-2e98-11e7-8dd5-e494e903d4c1.png)

but you're right, we should add more information in the category detail section.

> It would be nice if I didn't have to include the tokens in the ### .csv file I upload, and that it would automatically assign them.

just leave the corresponding "column" blank, as in:

`,Name Surname,email@host.tld,lang`

then alf.io should assign the first available token (the first one which has not been sent yet) based on history. You can of course discard an history item from the "history" tab.

Could you please confirm that this works for you?

Thanks!
Celestino

**Comment by alexdobo** [comment]
I just tested it, and it works not including the token in the csv
I just didn't read it properly when I made the csv a few days ago

**Comment by cbellone** [comment]
should be fixed now
