### ISSUE TITLE
Additional option are calculated wrong

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#292]
I have added an additional option called "Reserve money" with policy "One_Per_Ticket_Mandatory"

When I ordered 2 tickets, it added 3 additional options (see image)

![image](https://cloud.githubusercontent.com/assets/3386108/26491312/697d2500-420f-11e7-8471-aeb2ddc0b36e.png)

**Comment by syjer** [comment]
missed deploy. should be fixed
