### ISSUE TITLE
I need an invoice not working for "Outside EU"

### ISSUE THREAD

**Issue by yankedev** [exteso/alf.io#293]
I have done an reservation and selected the "I need an invoice" option.
I've inserted my billing addres for a "Non EU" but I cannot submit my order because of an error in the GUI (see image)

![image](https://cloud.githubusercontent.com/assets/3386108/26494437/fca22fe2-421e-11e7-8e4e-7c19fe41c6a6.png)

**Comment by syjer** [comment]
Should be fixed.
