### ISSUE TITLE
Demo mode

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#299]
Since we're receiving a lot of requests for that, it's time to create a demo.alf.io instance, so that people can try alf.io out without installing and configuring it.

To do that, we would need a new "demo" profile. 

I would propose the following:

### Login:

- we should display a message on the login page, something like: "this instance is in _demo mode_, please enter your email address, a password and click on _login_"
- the login fields are: "email address", "password"
- add a recaptcha "I'm not a robot" check (?)
- the login process will trigger a new organization creation. Organization email = user email. 

### Event Creation:
- the user can create as many events as he/she wants, but he/she cannot publish them (error from server: "cannot publish events in demo mode for privacy reasons")

### Payment:

- stripe: we should include the link to the credit cards test numbers
- paypal: we should specify username and password of the buyer test account
- mollie: tbd

### Reservation Flow:
- add a warning in the confirmation email: "THIS IS A TEST"

## Data cleanup:
on logout / every night at a random hour: delete user, org and events

**Comment by syjer** [comment]
TBD:

 - [ ] stripe link to test CC number
 - [ ] paypal: specify test user/pwd
 - [ ] reservation flow: add a this is a test in the email

**Comment by syjer** [comment]
can be considered implemented.
