### ISSUE TITLE
Lazy loading of tickets

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#318]
Remove tickets from `/admin/api/events/eventname.json` response. 
This will improve performances of the event detail page, especially in case of slow internet connection or big-size events.

The tickets should be loaded on-demand when the user clicks on the "tickets" button on a specific category.

**Comment by syjer** [comment]
As it's a quite large change, it will be done step by step by removing the use of the full event+categories+ticket:

Optimize pending payments mvc controllers call:
 - /events/{eventName}/pending-payments
 - implement /events/{eventName}/pending-payments-count

**Comment by syjer** [comment]
Will need to remove: eventStatisticsManager.fillWithStatistics which is a big bottleneck

**Comment by syjer** [comment]
TicketReservationManager.fetchWaitingForPayment -> we have a n+1 sql call here.

**Comment by syjer** [comment]
To fix: check-in list seems to be broken, looks like the loading was done implicitely as a side effect

**Comment by syjer** [comment]
Remove 
 - [ ] EventStatisticsManager.getSingleEventWithStatistics
 - [ ] EventWithStatistics -> switch to EventStatisticView
 - [ ] TicketCategoryWithStatistic -> switch to TicketCategoryStatisticView

**Comment by syjer** [comment]
TODO:

 - [ ] lazy load tickets in each ticket category in event view
 - [ ] fix stats in event overview

**Comment by syjer** [comment]
should be done
