### ISSUE TITLE
offline check-in data: support delta requests + optional data

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#319]
It would be useful, especially in case of big events, to load only the recently updated data from the server.
We should modify `/check-in/{eventName}/offline` in order to accept the following parameters:
- timestamp, for loading all the modified tickets from this date 
- additionalFields, default "company", list of additional fields to include in the response

in order to avoid clock sinchronization issues, the response should include also the timestamp from the server

**Comment by syjer** [comment]
- use auditing data for filtering
 - update auditing table when checkin is done (check if it is already done)

**Comment by syjer** [comment]
- [ ] Add event_id to auditing table + index, so we can filter on it more easily?
 - [ ] Create view LATEST_TICKET_UPDATE: 

```sql
select cast(entity_id as int) ticket_id, max(event_time) last_update from auditing where entity_type = 'TICKET' group by ticket_id
```

**Comment by syjer** [comment]
should be completed on this side.

**Comment by syjer** [comment]
We need to stream the output, as the first load can be too big anyway to be kept in memory.

**Comment by syjer** [comment]
change the synchronization api:

 -> fetch all the hashed identifier that has changed (or all)
 -> iterate over the hashed identifier: then create a new api to get blocks of N encrypted user data by sending the hashed identifier (by 200*) (using range)

**Comment by syjer** [comment]
should finally be done on this side :)
