### ISSUE TITLE
Set Checkin-date on category

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#333]
Full support for multi-day events will come with v2.0 (along with other things) 
For now we must at least support limited check-in, so that organizers can create multi-day events with combi tickets, or they can just create a special ticket for a fraction of the day.  

To do that we should add "check-in-from" _(default to event start at 00:00)_ and "check-in-to" _(default to event end)_ to each category

#### Example1: three days conference
Day1 (2017-09-11): workshops
Day2 (2017-09-12): main event
Day3 (2017-09-13): other workshops / unconference / whatever

in this case the organizer should define the following categories:
- "day1", check-in from: 2017-09-11 00:00 to 2017-09-11 23:59
- "day2", check-in from: 2017-09-12 00:00 to 2017-09-12 23:59
- "day3", check-in from: 2017-09-13 00:00 to 2017-09-13 23:59
- "full monty", check-in from: 2017-09-11 00:00 to 2017-09-13 23:59

#### Example1: one day conference
Day1 - main event (2017-09-11 08:00 - 16:00)
Day1 - meet & greet (2017-09-11 16:00 - 20:00)

in this case the organizer should define the following categories:
- "main event + meet & greet", check-in from: 2017-09-11 00:00 to 2017-09-11 20:00
- "meet & greet", check-in from: 2017-09-11 16:00 to 2017-09-12 20:00

**Comment by syjer** [comment]
TODO: 

 - [ ] save date on creation/update of ticket category
 - [ ] add check on check in code -> will need to modify the alf.io-PI and mobile app code?
 - [ ] ???

**Comment by syjer** [comment]
should be implemented
