### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by lpre9776** [exteso/alf.io#358]
Is there any way to change the QR code to a standard barcode ?

**Comment by syjer** [comment]
hi @lpre9776 , the QR Code contains a code which composed of 80~ characters (there is a checksum and additional data). I'm not aware of a linear barcode that is able to represent 80+ characters.

So no, there is no way to change it.

**Comment by lpre9776** [comment]
Is there any way to have the Reference number in a barcode format? So someone can use a laptop and scanner to check people on via scanning that code and searching ?

**Comment by syjer** [comment]
what do you mean by reference number? But as I said before, the identifier is too long to be visualized in a linear barcode.

**Comment by lpre9776** [comment]
The number on the ticket example: 31cbefae-d7790-48ec-bec6-751336ba293b

**Comment by syjer** [comment]
ok, but as far as I know, there is no linear barcode able to represent that much data (without breaking in multiple barcode)

**Comment by lpre9776** [comment]
What if it could be just the ending digits to help search tickets faster?

**Comment by syjer** [comment]
What would be the use case? As there is already an android (https://play.google.com/store/apps/details?id=alfio.backoffice) and IOS app (https://itunes.apple.com/us/app/alf-io/id1203898610) .

**Comment by lpre9776** [comment]
What is there is no internet connection ?

**Comment by syjer** [comment]
I don't see how the lack of internet is related with the mobile app.

**Comment by lpre9776** [comment]
Will the mobile app be able to load all the tickets during the event if there is no internet ?

**Comment by syjer** [comment]
Then, where would you search the ticket?

**Comment by syjer** [comment]
I mean, maybe I'm missing some information, but could you explain your whole use case? And how would you proceed?

**Comment by syjer** [comment]
(As a side note, we have the following project https://github.com/exteso/alf.io-PI that store locally all the tickets)

**Comment by lpre9776** [comment]
We are planning to use for a local sport event and don’t have great internet connection. So would the app be able to scan the tickets ? I’ve downloaded the app and tested. I’ll have to look at the local storing

**Comment by syjer** [comment]
Ok, I see, the mobile app don't have a local storage, so your use case, without  https://github.com/exteso/alf.io-PI (which require quit a lot of additional hardware) is not really possible right now.
