### ISSUE TITLE
support generic input/textarea field when assigning a ticket

### ISSUE THREAD

**Issue by syjer** [exteso/alf.io#46]
Currently we support (and they are always visible) the following optional fields:

 - Job title
 - Company
 - Phone number
 - Address
 - Country
 - T-Shirt size
 - Notes

We should let the admin decide:

 - the fields (name (multilanguage!), type (simple text, checkbox, radio, select, country), optional), their order.

:warning: this task has an heavy impact on the DB schema

**Comment by syjer** [comment]
datamodel:

table ticket_field_configuration

 - id
 - event_id_fk
 - lang : varchar
 - field_name : varchar
 - field_type (boolean, text, textarea, select, select_country) : enum
 - field_restricted_values (for select, serialized json array) : text
 - required : boolean


table ticket_field_value

- id
- ticket_field_configuration_id_fk
- value

**Comment by syjer** [comment]
TODO:

 - [ ] schema change
 - [ ] model + repository + service layer
 - [ ] update admin
 - [ ] update user facing ui
 - [ ] cleanup/migration schema

**Comment by syjer** [comment]
can be considered done.

**Comment by praburajaraman** [comment]
optional fields selected in admin ui is not showing in user reservation UI
