### ISSUE TITLE
Add "express checkout" option

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#55]
In case of single-ticket reservation, add the "I am buying the ticket for myself" option in order to completely skip the assignment process

**Comment by syjer** [comment]
taking care of it.

**Comment by syjer** [comment]
this task is blocked by #46 and #38

**Comment by cbellone** [comment]
moved to 1.6

**Comment by cbellone** [comment]
Hi Patrick (@patbaumgartner) and Matthijs (@mg-1999),
could you please provide a translation for the following text?

```
This ticket is for myself. Please assign it directly to me. 
```

thank you very much for your help!
Celestino

**Comment by mg-1999** [comment]
The translation of that into Dutch is:
````
Dit ticket is voor mezelf. Wijs het direct toe aan mij.
`````

You're welcome!
Matthijs
