### ISSUE TITLE
support multi tenancy

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#56]
Create a separate configuration for:

1) system
2) event
3) category

the settings should be applied in reverse order.
In order to differentiate events and avoid name clashing, the events should be named as user/eventName

**Comment by syjer** [comment]
Actually, it would be better to have the configuration at the following levels (add organization level):

1) system
2) organization
3) event
4) category

and the event should be on the organization/eventName url.

**Comment by syjer** [comment]
TODO: 

- [ ] pass the most precise 'context' to the ConfigurationManager calls where possible
- [ ] implement the db changes (new tables? modify the current configuration table?)
- [ ] implement the selection logic in ConfigurationManager
- [ ] implement admin GUI

**Comment by syjer** [comment]
The backend is done.
