### ISSUE TITLE
Updated Tutorial/Instructions

### ISSUE THREAD

**Issue by denboe** [exteso/alf.io#74]
Hi Alf.io!
I thought this was fantastic software that I stumbled across. I decided to give it a shot.
I am a very beginner / hobbyist programmer, so using many of these tools is new to me. However, the tutorial page made it fairly straight forward.

In the README it says: 
2. Follow the section "Deploying your WAR and EAR files using SCP/SFTP" from https://help.openshift.com/hc/en-us/articles/202399740-How-to-deploy-pre-compiled-java-applications-WAR-and-EAR-files-onto-your-OpenShift-gear-using-the-java-cartridges
	- follow point 2,3,4 (clone the repo, remove src and pom.xml, commit and push)

However, that website no longer exists, so I didnt have enough detail to finish the setup process.
Any help would be really appreciated - I would love to try this out.

Regards,
Dennis

**Comment by denboe** [comment]
Just an update. I tried to puzzle out the steps for myself and managed to get the .war into the wildfly/standalone folder. However, when viewing the domain all I can see it the words "EVENTS" and the option to switch between italian/english. I checked the server.log and wasn't able to find a first time login admin password. .

**Comment by cbellone** [comment]
Hi Dennis,
Thank you so much for giving it a try!

The information in the install-on-openshift.txt are outdated, sorry for that. Could you please refer to the new (and "official") guide?

http://alf.io/tutorials/openshift/

At the very end there are also the instructions on "how to get the generated password" from wildfly.

Should you have further questions about the installation/configuration procedure please write us on the mailing list:

https://groups.google.com/d/forum/alfio

We're trying to create a sort of "Q&A" section there.

Thank you!
Celestino
