### ISSUE TITLE
Cant insert address

### ISSUE THREAD

**Issue by mg-1999** [exteso/alf.io#76]
When I try to add an address to an event, it says that it cant find the address. I've tried it in any format I could think off. How to fix this?

**Comment by cbellone** [comment]
Hi @mg-1999,

Did you create and set the Google Maps' API Keys? (Both server and Browser)
If not, you can create an application here: https://console.developers.google.com/
then go under APIs & Auth -> Credentials and click on Add Credential -> API Key.
You must do it twice, one time for the Server API Key and the other for the Browser API Key (Client).

After doing that, do not forget to enable the following services under APIs & auth -> APIs:

- Google Maps Geocoding API	
- Google Maps Time Zone API	
- Google Static Maps API

that's it. After adding the keys to the Alfio's configuration, you should be able to find an address and to show it on a map.

Celestino

**Comment by mg-1999** [comment]
It works now. Only if I hit the 'save' button nothing happens, and no errors appear in config. Also every field has been filled in.

**Comment by cbellone** [comment]
Which version are you using?
Il 24-set-2015 09:31 PM, "Matthijs" <notifications@github.com> ha scritto:

**Comment by mg-1999** [comment]
Version 1.5, downloaded just a few days ago.

**Comment by cbellone** [comment]
Please upgrade to 1.5.1 as 1.5 could have problems on some cloud
environments. However, this shouldn't have nothing to do with your problem.

Please could you open the browser dev toolbar (F12 on some browsers) click
again on the button and see if something strange happens?

Could you also answer the questions below?

- Is the problem reproducible?
- If yes, could you please explain in detail what exactly we should do to
reproduce it?
- Could you plese send us the alfio.log file? (please remove the
auto-generated password first)

Thank you
Celestino
Il 24-set-2015 09:41 PM, "Matthijs" <notifications@github.com> ha scritto:

**Comment by mg-1999** [comment]
I just fill everything in, add a category and hit save. Also the Chrome Dev Tools is giving an error in the console, I will attach it to this post.

The log:
        [INFO ] 2015-09-24 15:23:18.013 [main] SpringBootLauncher - requested profiles 
        [INFO ] 2015-09-24 15:23:20.416 [main] SpringBootLauncher - Starting SpringBootLauncher on server.mg-dev.eu with PID 20878 (started by root in /root/alf)
        [WARN ] 2015-09-24 15:23:22.827 [main] PathMatchingResourcePatternResolver - Skipping [/root/alf/alfio-1.5-boot.war] because it does not denote a directory
        [INFO ] 2015-09-24 15:23:25.939 [main] DataSourceConfiguration - Detected DEFAULT cloud provider
[INFO ] 2015-09-24 15:23:35.873 [main] DataSourceConfiguration - Quartz scheduler configured to run!
[INFO ] 2015-09-24 15:23:40.022 [main] ConfigurationStatusChecker - performing migration from previous version, if any
[INFO ] 2015-09-24 15:23:40.202 [main] ConfigurationStatusChecker - done.
[INFO ] 2015-09-24 15:23:40.206 [main] ConfigurationStatusChecker - initialized alf.io version 1.5 
[INFO ] 2015-09-24 15:23:40.478 [QuartzScheduler_Worker-8] FileUploadManager - removed 0 unused file_blob
[INFO ] 2015-09-24 15:23:40.564 [main] SpringBootLauncher - Started SpringBootLauncher in 22.061 seconds (JVM running for 26.467)
[INFO ] 2015-09-24 15:23:40.568 [main] SpringBootLauncher - active profiles: dev-psql, spring-boot
[WARN ] 2015-09-24 15:24:00.450 [qtp2138369213-18] PageNotFound - No mapping found for HTTP request with URI [/favicon.ico] in DispatcherServlet with name 'dispatcherServlet'

The errors in the console:
![alf](https://cloud.githubusercontent.com/assets/6923382/10085376/29199ee4-6309-11e5-8627-1a1ca66a26a8.png)

**Comment by cbellone** [comment]
Ok, this is why you don't see any error message in the page. Thank you.
Looks like there is something wrong with the content of the form.
Could you please open the "network" tab, clear the entries and then click
on the button?
It should appear an ajax "check" call.
Could you please export it as har and send it? (please remove all the
sensitive data, if any but leave dates as they are)
Il 24-set-2015 10:12 PM, "Matthijs" <notifications@github.com> ha scritto:

**Comment by mg-1999** [comment]
Which button do I need to click on? Because there are lots of buttons.

**Comment by mg-1999** [comment]
Got it:

**Comment by mg-1999** [comment]
Any progress?

**Comment by syjer** [comment]
Hi, @mg-1999 

from the trace it seems the issue is caused by the dates (start/end) : they have all the same values: "2015-09-25 15:00 / 2015-09-25 15:00". This is not handled by alf.io, as he need an interval of time greater than 0 :)

An error message should appear but for some reason that we need to investigate it's not visibile.

**Comment by mg-1999** [comment]
It is indeed fixed now, forgot to hit the apply button. Thanks for all the help you provided.
