### ISSUE TITLE
Paypal integration

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#77]
Even if stripe is a great API, it is not (yet) available on all countries. Maybe we should integrate also paypal.
It seems that there is an official REST (OAUTH?) API:
https://developer.paypal.com/docs/api/

**Comment by alexproca** [comment]
+1 for paypal integration

**Comment by cbellone** [comment]
Hi @alexproca,

Thank you for your interest in alf.io!

As you can see, Paypal integration is not on the roadmap right now, so it would be great if you could provide a pull request for that. WDYT?

Thank you very much!
Celestino

**Comment by cbellone** [comment]
Due to the high amount of requests from a lot of users, this feature will be implemented in the upcoming version 1.8

**Comment by syjer** [comment]
taking care of it :).

Doc link: https://developer.paypal.com/docs/classic/express-checkout/integration-guide/ECGettingStarted/

**Comment by syjer** [comment]
To be done:

 - [ ] remove all hardcoded values
 - [ ] error handling
 - [ ] ui/ux cleanup
 - [ ] translations
 - [ ] fetch correct transaction id
 - [ ] fix "payment experience"

**Comment by syjer** [comment]
Hi @mg-1999 , could you provide the translations for the following texts ?

- Confirm paypal payment
- Confirm to continue.
- Pay with your paypal account. You will be redirected to paypal.com.
- Error in returned data: they may have been modified. You have not been charged. Please try again.

Thank you :)

**Comment by cbellone** [comment]
has been implemented :-)

**Comment by mg-1999** [comment]
Hello guys,

A little late to the party, but time was on my side. The translation to dutch for the requested sentences are:

- Bevestig paypal betaling
- Bevestig om verder te gaan
- Betaal met je paypal account. U wordt doorverwezen naar paypal.com.
- Fout in ontvangen gegevens: ze zijn waarschijnlijk aangepast. Er zijn geen kosten in rekening gebracht. Probeer later opnieuw.

**Comment by syjer** [comment]
Hi @mg-1999 , thanks for the translations ! I'll add them ASAP
