### ISSUE TITLE
Cant load scan page video source

### ISSUE THREAD

**Issue by mg-1999** [exteso/alf.io#79]
I was trying the scan page but found out that then video source is not loading, I get some errors as seen in the image below.

![image](https://cloud.githubusercontent.com/assets/6923382/10305932/a897f706-6c23-11e5-88b4-7c7af129dbab.png)

**Comment by cbellone** [comment]
Hi @mg-1999,

yep, this is a bug. Thank you for pointing it out. We'll fix it in the next version.
Meanwhile you can try to scan your tickets using the android app. https://github.com/exteso/AlfioCheckIn
the UI is still "work in progress" and you have to build it by yourself but it works (we already used it to scan 300 tickets at our conference)

**Comment by syjer** [comment]
fixed :).

Thanks for the bug report.

**Comment by cbellone** [comment]
Hi @mg-1999, fyi we just published the new version of the Check-in application (now is back-office) to the google play store.
At this stage it is yet in private beta but you should already have the grants to view and download it:
https://play.google.com/apps/testing/alfio.backoffice

it would be great if you could test it and report bugs on https://github.com/exteso/Alf.ioBackoffice

Thank you in advance!
Celestino

**Comment by mg-1999** [comment]
Gonna look into it when I'm back home.
