### ISSUE TITLE
Language doesn't transfer when switching page.

### ISSUE THREAD

**Issue by mg-1999** [exteso/alf.io#80]
Title says it all, tested it on the 1.5.1 version.

**Comment by cbellone** [comment]
Sorry I don't understand what's wrong. Could you please provide more
details about it? How could I reproduce it?
Thank you!
Il 8-ott-2015 06:05 PM, "Matthijs" <notifications@github.com> ha scritto:

**Comment by mg-1999** [comment]
I select a language on the homepage (Dutch) and then click on the event. When I go to the event the language changes back to English. This also happens with every other language supported.

**Comment by cbellone** [comment]
Tested, didn't find the problem.
I think that the Dutch language has not been activated in the event configuration (edit event -> available languages)
could you please verify that?

Thank you
Celestino

**Comment by mg-1999** [comment]
Yes that was the problem.

Thank you for all the help,
Matthijs
