### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#9]
Add support for Markdown in the description field for both event and ticket category

**Comment by syjer** [comment]
taking care of it

**Comment by syjer** [comment]
finally implemented :)

**Comment by gBaylaender** [comment]
Hello guys, the markdown doesn't support the table, for example:

| 11:00 | Check in (lunch not included) |
|-------|-------------------------------|
| 13:00 | First Session                 |
| 14:00 | Coffee Break                  |
| 15:00 | Second Session                |
| 16:00 | Coffee Break                  |
| 17:00 | Third Session                 |
| 19:15 | Aperitivo                     |

it's appearing like:

<img width="779" alt="Screen Shot 2019-07-02 at 21 29 49" src="https://user-images.githubusercontent.com/1658712/60541028-e3e53e00-9d10-11e9-897e-7da116c24d64.png">

**Comment by syjer** [comment]
@gBaylaender , I've opened a new issue about your specific problem (#677 )
