### ISSUE TITLE
add an additional field while editing an event

### ISSUE THREAD

**Issue by cbellone** [exteso/alf.io#91]
Currently the user can edit an existing additional field but he/she cannot insert a new one

**Comment by syjer** [comment]
Check country field. It seems that it create an input instead of a select

**Comment by syjer** [comment]
TODO:
 - [ ] add additional fields
 - [ ] delete additional fields (with warning)

**Comment by syjer** [comment]
can be considered done. Additional work in validation will be done in the rewamped admin.
